"""misc changes

Revision ID: 3f6be6fc58a9
Revises: c649c05e964c
Create Date: 2023-07-13 16:18:57.424694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6be6fc58a9'
down_revision = 'c649c05e964c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('service', sa.String(), nullable=True))
    op.drop_column('consultations', 'location')
    op.drop_column('consultations', 'phoneNumber')
    op.drop_column('consultations', 'email')
    op.drop_column('consultations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consultations', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consultations', sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consultations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('consultations', 'service')
    # ### end Alembic commands ###
