"""agent_name column added to property and diaspora table

Revision ID: a7770f46859c
Revises: 5d680f667edc
Create Date: 2023-07-11 09:53:22.837428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7770f46859c'
down_revision = '5d680f667edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agents', ['id'])
    op.create_unique_constraint(None, 'agents', ['name'])
    op.add_column('diasporaPropertyListings', sa.Column('agentName', sa.String(), nullable=False))
    op.create_foreign_key(None, 'diasporaPropertyListings', 'agents', ['agentName'], ['name'], ondelete='CASCADE')
    op.add_column('propertyListings', sa.Column('agentName', sa.String(), nullable=False))
    op.create_foreign_key(None, 'propertyListings', 'agents', ['agentName'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propertyListings', type_='foreignkey')
    op.drop_column('propertyListings', 'agentName')
    op.drop_constraint(None, 'diasporaPropertyListings', type_='foreignkey')
    op.drop_column('diasporaPropertyListings', 'agentName')
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_constraint(None, 'agents', type_='unique')
    # ### end Alembic commands ###
