"""new database changes

Revision ID: c37ef1c87d09
Revises: 3f6be6fc58a9
Create Date: 2023-07-13 18:51:08.187285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37ef1c87d09'
down_revision = '3f6be6fc58a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'service',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('propertyRequests', sa.Column('preferredService', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propertyRequests', 'preferredService')
    op.alter_column('consultations', 'service',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
