"""misc changes

Revision ID: c649c05e964c
Revises: c45539ebd34a
Create Date: 2023-07-13 13:57:36.655555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c649c05e964c'
down_revision = 'c45539ebd34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diasporaPropertyListings', sa.Column('description', sa.String(), nullable=True))
    op.add_column('propertyListings', sa.Column('description', sa.String(), nullable=True))
    op.add_column('propertyRequests', sa.Column('requestType', sa.String(), nullable=False))
    op.add_column('propertyRequests', sa.Column('budget', sa.String(), nullable=False))
    op.drop_column('propertyRequests', 'budgetRange')
    op.drop_column('propertyRequests', 'numberOfrooms')
    op.drop_column('propertyRequests', 'maxBudget')
    op.drop_column('propertyRequests', 'notes')
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.add_column('propertyRequests', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('propertyRequests', sa.Column('maxBudget', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('propertyRequests', sa.Column('numberOfrooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('propertyRequests', sa.Column('budgetRange', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('propertyRequests', 'budget')
    op.drop_column('propertyRequests', 'requestType')
    op.drop_column('propertyListings', 'description')
    op.drop_column('diasporaPropertyListings', 'description')
    # ### end Alembic commands ###
