"""agent_name column added to property and diaspora table"

Revision ID: fa10409a56ae
Revises: 5d680f667edc
Create Date: 2023-07-11 09:30:32.585547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa10409a56ae'
down_revision = '5d680f667edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diasporaPropertyListings', sa.Column('agentName', sa.String(), nullable=False))
    op.create_foreign_key(None, 'diasporaPropertyListings', 'agents', ['agentName'], ['name'], ondelete='CASCADE')
    op.add_column('propertyListings', sa.Column('agentName', sa.String(), nullable=False))
    op.create_foreign_key(None, 'propertyListings', 'agents', ['agentName'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propertyListings', type_='foreignkey')
    op.drop_column('propertyListings', 'agentName')
    op.drop_constraint(None, 'diasporaPropertyListings', type_='foreignkey')
    op.drop_column('diasporaPropertyListings', 'agentName')
    # ### end Alembic commands ###
