name: Build, Test and Deploy to Heroku

on:
  push:
    branches:
      - main
      - admin
  # pull_request:
  #   branches:
  #     - main
  #     - admin

jobs:
  build:
    environment:
      name: staging
    runs-on: ubuntu-20.04
    env:
      # environment variable using github secrets
      DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRATION_IN_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRATION_IN_MINUTES }}
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.1
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        # run: pytest
        run: echo "No tests"

  deploy:
    needs: build
    environment:
      name: Production
    runs-on: ubuntu-20.04
    steps:
      # pull github repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # push to heroku using heroku-cli
      # - name: Install Heroku CLI
      #   run: |
      #     curl https://cli-assets.heroku.com/install.sh | sh
      # login to heroku
      # - name: Login to Heroku
      #   run: heroku container:login
      # add heroku remote
      # - name: Add Heroku remote
      #   run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
      # push to heroku
      # - name: Push to Heroku
      #   run: |
      #     heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
      #     heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      # auto deploy to heroku
      - name: Deploy to Heroku
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.6
        with:
          herokuApiKey: ${{ secrets.HEROKU_API_KEY }}
          herokuAppName: ${{ secrets.HEROKU_APP_NAME }}
